In [2]:
import torch
torch.rand(10).to("cuda")

tensor([0.7254, 0.9961, 0.5620, 0.4830, 0.6784, 0.2463, 0.3757, 0.8065, 0.9240,
        0.3080], device='cuda:0')

In [3]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
c = torch.cat([a, b], dim=0)
print(c)  # tensor([1, 2, 3, 4])
print(c.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [5]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
c = torch.stack([a, b], dim=0)
print(c)
print(a.shape)
print(c.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2])
torch.Size([2, 2])


In [1]:
import pickle
with open("/data/data2/IRRA/COCO/vocab.pkl","rb") as fr:
    vocab = pickle.load(fr)
len(vocab)

26964

In [2]:
import numpy as np

mask = np.hstack([
    np.zeros(196 - 147), # UNMASK
    np.ones(147),                     # MASK
])
tmp = mask
tmp

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
mask2 = np.hstack([
    np.zeros(196 - 147), # UNMASK
    np.ones(147),                     # MASK
])
tmp2 = mask2
tmp2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
print(tmp.shape)

(196,)


In [5]:
import torch
# numpy 배열을 PyTorch 텐서로 변환
tensor_a = torch.tensor(tmp)

# 텐서의 형태를 [1, 196]으로 변경
tensor_a = tensor_a.view(1, -1)

print(tensor_a.shape)  # 결과: torch.Size([1, 196])


torch.Size([1, 196])


In [10]:
import torch
# numpy 배열을 PyTorch 텐서로 변환
tensor_b = torch.tensor(tmp2)

# 텐서의 형태를 [1, 196]으로 변경
tensor_b = tensor_b.view(1, -1)

print(tensor_b.shape)  # 결과: torch.Size([1, 196])


torch.Size([1, 196])


In [11]:
tensor_b

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
       dtype=torch.float64)

In [8]:
tensor_a

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
       dtype=torch.float64)

In [14]:
tensor_a.shape

torch.Size([1, 196])

In [15]:
tensor_b.shape

torch.Size([1, 196])

In [17]:
result = torch.stack((tensor_a, tensor_b), dim=0)
result.shape

torch.Size([2, 1, 196])

In [18]:
import torch

# 예시 tensor_a와 tensor_b
tensor_a = torch.randn(1, 196)
tensor_b = torch.randn(1, 196)

# torch.stack을 사용하여 두 텐서를 쌓기
result = torch.stack((tensor_a, tensor_b), dim=0)

print(result.shape)  # 결과: torch.Size([2, 196])


torch.Size([2, 1, 196])


In [19]:
import torch

# 예시 tensor_a와 tensor_b
tensor_a = torch.randn(1, 196)
tensor_b = torch.randn(1, 196)

# torch.cat을 사용하여 두 텐서를 연결하기
result = torch.cat((tensor_a, tensor_b), dim=0)

print(result.shape)  # 결과: torch.Size([2, 196])


torch.Size([2, 196])


In [13]:
c = torch.stack([tensor_a, tensor_b], dim=0)
c.shape

torch.Size([2, 1, 196])

In [2]:
type(vocab)

tokengt_datasets.vocab.Vocabulary

In [4]:
vocab

In [3]:
import torch

# 로드할 .pth 파일 경로
file_path = '/data/data2/khahn/coco_irra_edge_masking/tmp_logs/RSTPReid/20230709_112656_iira/best.pth'

# .pth 파일 로드
loaded_data = torch.load(file_path)

# 로드한 데이터 사용 예시
model = loaded_data['model']
optimizer = loaded_data['optimizer']
epoch = loaded_data['epoch']

# 사용 예시 출력
print("Loaded model:", model)
# print("Loaded optimizer:", optimizer)
# print("Loaded epoch:", epoch)


Loaded model: OrderedDict([('encoder.graph_encoder.graph_feature.id_encoder.weight', tensor([[-0.0265,  0.0214,  0.0138,  ...,  0.0262, -0.0309, -0.0184],
        [-0.0187, -0.0108, -0.0391,  ..., -0.0076, -0.0194,  0.0063],
        [ 0.0411, -0.0053,  0.0246,  ...,  0.0084,  0.0166, -0.0188],
        ...,
        [-0.0004,  0.0412, -0.0165,  ..., -0.0306, -0.0318, -0.0165],
        [ 0.0129,  0.0256,  0.0195,  ..., -0.0121,  0.0207, -0.0234],
        [ 0.0387,  0.0065,  0.0181,  ...,  0.0377,  0.0232,  0.0430]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.graph_token.weight', tensor([[-0.0307,  0.0046, -0.0120,  ...,  0.0148,  0.0037,  0.0140]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.null_token.weight', tensor([[ 0.0188,  0.0077, -0.0026,  ...,  0.0197, -0.0037, -0.0122]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.lap_encoder.weight', tensor([[-6.8331e-04, 

In [3]:
model.keys()

odict_keys(['encoder.graph_encoder.graph_feature.id_encoder.weight', 'encoder.graph_encoder.graph_feature.graph_token.weight', 'encoder.graph_encoder.graph_feature.null_token.weight', 'encoder.graph_encoder.graph_feature.lap_encoder.weight', 'encoder.graph_encoder.graph_feature.order_encoder.weight', 'encoder.graph_encoder.emb_layer_norm.weight', 'encoder.graph_encoder.emb_layer_norm.bias', 'encoder.graph_encoder.final_layer_norm.weight', 'encoder.graph_encoder.final_layer_norm.bias', 'encoder.graph_encoder.layers.0.self_attn.k_proj.weight', 'encoder.graph_encoder.layers.0.self_attn.k_proj.bias', 'encoder.graph_encoder.layers.0.self_attn.v_proj.weight', 'encoder.graph_encoder.layers.0.self_attn.v_proj.bias', 'encoder.graph_encoder.layers.0.self_attn.q_proj.weight', 'encoder.graph_encoder.layers.0.self_attn.q_proj.bias', 'encoder.graph_encoder.layers.0.self_attn.out_proj.weight', 'encoder.graph_encoder.layers.0.self_attn.out_proj.bias', 'encoder.graph_encoder.layers.0.self_attn_layer_no

In [9]:
state_dict = model  # collections.OrderedDict 객체

# 특정 키들 확인
keys = state_dict.keys()

# 키들 중에 주어진 키들이 있는지 확인
has_key_1 = "cross_attn.in_proj_weight" in keys
has_key_2 = "cross_attn.in_proj_bias" in keys
has_key_3 = "cross_attn.out_proj.weight" in keys
has_key_4 = "cross_attn.middle" in keys

# 결과 출력
print("Has cross_attn.in_proj_weight:", has_key_1)
print("Has cross_attn.in_proj_bias:", has_key_2)
print("Has cross_attn.out_proj.weight:", has_key_3)
print("Has cross_attn.middle:", has_key_4)


Has cross_attn.in_proj_weight: True
Has cross_attn.in_proj_bias: True
Has cross_attn.out_proj.weight: True
Has cross_attn.middle: False


In [8]:
import torch

# 로드할 .pth 파일 경로
file_path = '/data/data2/yjkim/coco_irra/base_logs/COCO/pretrain_model/best.pth'

# .pth 파일 로드
loaded_data = torch.load(file_path)

# 로드한 데이터 사용 예시
model = loaded_data['model']
optimizer = loaded_data['optimizer']
epoch = loaded_data['epoch']

# 사용 예시 출력
print("Loaded model:", model)
# print("Loaded optimizer:", optimizer)
# print("Loaded epoch:", epoch)


Loaded model: OrderedDict([('encoder.graph_encoder.graph_feature.id_encoder.weight', tensor([[ 0.0166, -0.0087, -0.0071,  ...,  0.0013,  0.0165,  0.0257],
        [ 0.0101, -0.0074,  0.0202,  ..., -0.0154, -0.0016, -0.0115],
        [ 0.0146, -0.0282, -0.0252,  ..., -0.0183,  0.0183,  0.0171],
        ...,
        [-0.0128,  0.0165, -0.0331,  ..., -0.0062,  0.0341,  0.0207],
        [ 0.0182, -0.0154, -0.0175,  ..., -0.0007, -0.0236,  0.0091],
        [ 0.0042, -0.0106,  0.0024,  ..., -0.0021,  0.0087, -0.0181]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.graph_token.weight', tensor([[-0.0424, -0.0086,  0.0347,  ..., -0.0170,  0.0158, -0.0168]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.null_token.weight', tensor([[ 0.0034, -0.0040, -0.0173,  ..., -0.0433,  0.0368, -0.0086]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.lap_encoder.weight', tensor([[-0.0051,  0.0

In [9]:
state_dict = model  # collections.OrderedDict 객체

# 특정 키들 확인
keys = state_dict.keys()

# 키들 중에 주어진 키들이 있는지 확인
has_key_1 = "cross_attn.in_proj_weight" in keys
has_key_2 = "cross_attn.in_proj_bias" in keys
has_key_3 = "cross_attn.out_proj.weight" in keys
has_key_4 = "cross_attn.middle" in keys

# 결과 출력
print("Has cross_attn.in_proj_weight:", has_key_1)
print("Has cross_attn.in_proj_bias:", has_key_2)
print("Has cross_attn.out_proj.weight:", has_key_3)
print("Has cross_attn.middle:", has_key_4)


Has cross_attn.in_proj_weight: False
Has cross_attn.in_proj_bias: False
Has cross_attn.out_proj.weight: False
Has cross_attn.middle: False


In [10]:
import torch

# 로드할 .pth 파일 경로
file_path = '/data/data2/khahn/coco_irra_edge_masking/tmp_logs/RSTPReid/20230709_112656_iira/best.pth'

# .pth 파일 로드
loaded_data = torch.load(file_path)

# 로드한 데이터 사용 예시
model = loaded_data['model']
optimizer = loaded_data['optimizer']
epoch = loaded_data['epoch']

# 사용 예시 출력
print("Loaded model:", model)
# print("Loaded optimizer:", optimizer)
# print("Loaded epoch:", epoch)


Loaded model: OrderedDict([('encoder.graph_encoder.graph_feature.id_encoder.weight', tensor([[-0.0265,  0.0214,  0.0138,  ...,  0.0262, -0.0309, -0.0184],
        [-0.0187, -0.0108, -0.0391,  ..., -0.0076, -0.0194,  0.0063],
        [ 0.0411, -0.0053,  0.0246,  ...,  0.0084,  0.0166, -0.0188],
        ...,
        [-0.0004,  0.0412, -0.0165,  ..., -0.0306, -0.0318, -0.0165],
        [ 0.0129,  0.0256,  0.0195,  ..., -0.0121,  0.0207, -0.0234],
        [ 0.0387,  0.0065,  0.0181,  ...,  0.0377,  0.0232,  0.0430]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.graph_token.weight', tensor([[-0.0307,  0.0046, -0.0120,  ...,  0.0148,  0.0037,  0.0140]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.null_token.weight', tensor([[ 0.0188,  0.0077, -0.0026,  ...,  0.0197, -0.0037, -0.0122]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.lap_encoder.weight', tensor([[-6.8331e-04, 

In [10]:
import torch

# 로드할 .pth 파일 경로
file_path = '/data/data2/khahn/coco_irra_edge_masking/tmp_logs/RSTPReid/20230709_123329_iira/best.pth'

# .pth 파일 로드
loaded_data = torch.load(file_path)

# 로드한 데이터 사용 예시
models = loaded_data['model']
# optimizer = loaded_data['optimizer']
# epoch = loaded_data['epoch']

# 사용 예시 출력
print("Loaded model:", models)
# print("Loaded optimizer:", optimizer)
# print("Loaded epoch:", epoch)


Loaded model: OrderedDict([('encoder.graph_encoder.graph_feature.id_encoder.weight', tensor([[-0.0265,  0.0214,  0.0138,  ...,  0.0262, -0.0309, -0.0184],
        [-0.0187, -0.0108, -0.0391,  ..., -0.0076, -0.0194,  0.0063],
        [ 0.0411, -0.0053,  0.0246,  ...,  0.0084,  0.0166, -0.0188],
        ...,
        [-0.0004,  0.0412, -0.0165,  ..., -0.0306, -0.0318, -0.0165],
        [ 0.0129,  0.0256,  0.0195,  ..., -0.0121,  0.0207, -0.0234],
        [ 0.0387,  0.0065,  0.0181,  ...,  0.0377,  0.0232,  0.0430]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.graph_token.weight', tensor([[-0.0307,  0.0046, -0.0120,  ...,  0.0148,  0.0032,  0.0140]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.null_token.weight', tensor([[ 0.0188,  0.0077, -0.0026,  ...,  0.0197, -0.0038, -0.0129]],
       device='cuda:0', dtype=torch.float16)), ('encoder.graph_encoder.graph_feature.lap_encoder.weight', tensor([[-3.4261e-04, 

In [7]:
state_dict = models  # collections.OrderedDict 객체

# 특정 키들 확인
keys = state_dict.keys()

# 키들 중에 주어진 키들이 있는지 확인
has_key_1 = "cross_attn.in_proj_weight" in keys
has_key_2 = "cross_attn.in_proj_bias" in keys
has_key_3 = "cross_attn.out_proj.weight" in keys
has_key_4 = "cross_attn.middle" in keys

# 결과 출력
print("Has cross_attn.in_proj_weight:", has_key_1)
print("Has cross_attn.in_proj_bias:", has_key_2)
print("Has cross_attn.out_proj.weight:", has_key_3)
print("Has cross_attn.middle:", has_key_4)


Has cross_attn.in_proj_weight: True
Has cross_attn.in_proj_bias: True
Has cross_attn.out_proj.weight: True
Has cross_attn.middle: False
